### ISSUE TITLE
How can we retain the background in the final video?

### ISSUE THREAD

**Issue by amil-rp-work** [shrubb/latent-pose-reenactment#20]
Is there a possibility to retain the background in the resultant video?

**Comment by shrubb** [comment]
Sure, you just need to
1. somehow get the background (by some inpainting algorithm for example), and
2. change inference code to blend that background in place of the empty black region.

Or retrain the whole system without removing the background (but [the quality will be a bit lower](https://saic-violet.github.io/latent-pose-reenactment/)).

**Comment by amil-rp-work** [comment]
Okay got it
Thanks for sharing your thoughts!
