### ISSUE TITLE
how to run without training.

### ISSUE THREAD

**Issue by molo32** [shrubb/latent-pose-reenactment#23]
how to execute without training, that is, passing a driver image and another source image and generating the output without training.
I would like to use in real time with a webcam, each frame of the webcam would act as a "driver", and any image of a face as an avatar.

**Comment by shrubb** [comment]
To run with webcam, adjust data loading in "drive.py" and run as usual. I mean, replace [these lines](https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/drive.py#L73-L84) with something like this (not tested):

```python
from utils.crop_as_in_dataset import ImageWriter, ImageReader, LatentPoseFaceCropper

def numpy_image_to_torch(image):
    return torch.tensor(image.astype(np.float32) / 255.0).permute(2, 0, 1)

face_cropper = LatentPoseFaceCropper()
image_reader = ImageReader.get_image_reader('WEBCAM_0')
image_writer = ImageWriter.get_image_writer('SCREEN')

for driving_image in tqdm(image_reader):
    # Will be faster if run on GPU inside `LatentPoseFaceCropper`
    if max(driving_image.shape) > 1152:
        resize_ratio = 1152 / max(driving_image.shape)
        driving_image = cv2.resize(
            driving_image, dsize=None, fx=resize_ratio, fy=resize_ratio)

    driving_image_cropped, _ = face_cropper.crop_image(driving_image)
    driving_image_cropped = numpy_image_to_torch(driving_image_cropped)
    data_dict['pose_input_rgbs'] = driving_image_cropped[None]

    # drive
    # ...
```

**Comment by molo32** [comment]
but how can I train to use it on any avatar without fine tuning.
or should I train a .pth for each avatar?

**Comment by shrubb** [comment]
Of course you should. This is the core of our method. Otherwise there will be a huge identity gap. If you **really** want to run without fine-tuning, see #8.
