### ISSUE TITLE
som questions about fintune on certain person

### ISSUE THREAD

**Issue by visonpon** [shrubb/latent-pose-reenactment#24]
Hi @shrubb, when I try to finetune on a certain person, while the id keeps fine, but the expression does not go well, especially the mouth. so I'd like to ask some advice:
first, how many images would you suggest to finetune on a certain person and how to design this person's expression and pose distribution in order to get better results?
second, I also try to train higher resolution output based on your trained model(e.g,512), but the results are bad, and I also try to train from scratch, the id is fine but the expression reenactment seems not  work.
Hope you can give some advice, thanks~

**Comment by shrubb** [comment]
1 image is usually enough. But the more the better, of course (30 is more than enough I think) And the more diverse expressions/poses are, the better.

Hard to say what's happening... Have you tried fine-tuning for 1 or 0 iterations? The expression should definitely look OK in that case.
