### ISSUE TITLE
 a question

### ISSUE THREAD

**Issue by loveFaying** [shrubb/latent-pose-reenactment#25]
I want to know why after the addition is aligned, the big angle frame will have problems(Head down: ghosting). Is this prediction sensitive to the location information of the face?

**Comment by shrubb** [comment]
Sorry, didn't get the question (I suspect translation errors). What do you mean by "addition is aligned" and "location information"?

**Comment by loveFaying** [comment]
thank you reply.when I try to increase face alignment, I found out that there will be ghosting when I lower my head.
location infomation : I want to know whether the final prediction result is related to the position of the head in the image

**Comment by shrubb** [comment]
> I want to know whether the final prediction result is related to the position of the head in the image

Yes, it is. And it's important. The system was trained on images cropped [in a specific way](https://github.com/shrubb/latent-pose-reenactment/blob/2a876ff441fa4425465c1caa0fcdde2302641274/utils/crop_as_in_dataset.py), and thus must be evaluated on images cropped using the same algorithm.

**Comment by loveFaying** [comment]
thank you very much :)
