### ISSUE TITLE
About Graph

### ISSUE THREAD

**Issue by loveFaying** [shrubb/latent-pose-reenactment#26]
Thank you for your contribution，What drawing software do you use？，I strongly think your structure diagram is very beautiful。thank you :)

**Comment by shrubb** [comment]
:smiling_face_with_three_hearts: Thanks! I use MS PowerPoint for such diagrams.

**Comment by loveFaying** [comment]
Good，So beautiful！I have another question，，
I want to achieve an effect：The lighting of the result video follows the lighting of the input video. The purpose is to make the model produce different lighting effects. But I failed. Could it be that the model does not allow this?

**Comment by shrubb** [comment]
Yes, the model intentionally doesn't allow this. That was one of the main points of our paper.

If you want to allow lighting from driving images to influence the result, try switching off some of the [lighting augmentations](https://github.com/shrubb/latent-pose-reenactment/blob/master/dataloaders/common/augmentation.py) during training. No guarantee that it will work though, your goal is very ambitious.

**Comment by loveFaying** [comment]
Thank you for your reply and wish you success in your work
