### ISSUE TITLE
I found quite amount of datasets are missed in train.csv

### ISSUE THREAD

**Issue by seungjun-moon** [shrubb/latent-pose-reenactment#29]
Hello. I manually preprocessed all Voxceleb2 datasets for training the provided model from scratch.

However, I found that many hashes of videos in Voxceleb2 are missed in data/splits/train.csv.

Can I get the reason for standards whether to contain in the train.csv or not?

Anyway, thank you for providing an interesting paper.

**Comment by shrubb** [comment]
Hi, thanks. Actually, I don't remember this very well... I think we filtered videos based on reasons like:

- resolution is adequate, e.g. facial bounding boxes are at least 256 x 256;
- different people aren't mixed in one video (I remember this happened in default VoxCeleb2);
- download didn't fail.

Clearly, if you take more clean data and preprocess them properly, the results should still match.

**Comment by seungjun-moon** [comment]
Thank you for replying! Hope you have a nice day!
