### ISSUE TITLE
Image Shaking

### ISSUE THREAD

**Issue by nagadit** [shrubb/latent-pose-reenactment#3]
Help pls, my dst images look something like this
![Unknown](https://user-images.githubusercontent.com/24617421/98998341-0adb9300-2547-11eb-9cf0-61885c60ac2d.jpg)

and src looks like this
![1](https://user-images.githubusercontent.com/24617421/98998442-2e064280-2547-11eb-8d00-42700e88b541.jpg)

preprocess cfg looks like this

`DO_DECODE_VIDEOS=\
false

DO_CROP=\
true
DO_COMPUTE_SEGMENTATION=\
true
DO_COMPUTE_LANDMARKS=\
false
DO_COMPUTE_POSE_3DMM=\
false

DO_CROP_FFHQ=\
false
DO_COMPUTE_SEGMENTATION_FFHQ=\
false`

after fine-tuning and drive, my video is shaking, why can this be?

![ezgif-4-f7ba1155c0ec](https://user-images.githubusercontent.com/24617421/98998826-cd2b3a00-2547-11eb-9c7e-67710b2a27d7.gif)

 I assume this is due to the incorrect operation of the face tracker.

**Comment by shrubb** [comment]
Yes.
