### ISSUE TITLE
wrong index of inter-ocular in pose_reconstruction_error?

### ISSUE THREAD

**Issue by khlee369** [shrubb/latent-pose-reenactment#30]
Hi shrubb, good to see you again.

In ```pose_reconstruction_error``` ,
the landmark distance is normalized by inter-ocular distance.

 [```pose_reconstruction_error``` compute_pose_identity_error.py](https://github.com/shrubb/latent-pose-reenactment/blob/2a876ff441fa4425465c1caa0fcdde2302641274/compute_pose_identity_error.py#L290),
```py
def pose_reconstruction_error(gt_landmarks, our_landmarks, apply_optimal_alignment=False):
    assert gt_landmarks.shape == (len(IDENTITIES), NUM_VIDEO_FRAMES, 68, 2)
    assert our_landmarks.shape == gt_landmarks.shape

........

    interocular = np.linalg.norm(gt_landmarks[:, :, 36] - gt_landmarks[:, :, 45], 
axis=-1).clip(min=1e-2)
    normalized_distances = np.linalg.norm(gt_landmarks - our_landmarks, axis=-1) / interocular[:, :, None]
    return normalized_distances.mean()
```

but, according to the landmark index,

![image](https://user-images.githubusercontent.com/17489382/127083774-c354be14-ce05-4bc7-bb8e-c2c5530840da.png)

I think the distance between (index 36 - index 45) is not inter-ocular distance.

maybe (index 39 - index 42) i guess??

**Comment by shrubb** [comment]
Your index starts from 1, which is wrong. The correct index (check the `MEAN_FACE` variable) starts from 0 and is

![image](https://user-images.githubusercontent.com/9570420/127470295-a83c33b1-291d-4dab-a19f-f9e049b8f2df.png)

**Comment by khlee369** [comment]
I totally made a poor mistake LOL.....
thank you shurrb
