### ISSUE TITLE
cv2.COLOR_BGR2RGB is missing at get_identity_descriptor?

### ISSUE THREAD

**Issue by khlee369** [shrubb/latent-pose-reenactment#31]
At [```get_identity_descriptor```.compute_pose_identity_error.py](https://github.com/shrubb/latent-pose-reenactment/blob/2a876ff441fa4425465c1caa0fcdde2302641274/compute_pose_identity_error.py#L101-L106),

if the face detection gets failed, it manually crops and pre-processes the image.
and there is no channel conversion(BGR to RGB)

but if face detection gets succeed, ```arcface_model.get_input(image)``` convert image channels.[link](https://github.com/dniku/insightface/blob/763060b2608aaa9e77103ac6aaa393878501dee3/insightface/face_model.py#L67)

i think ```cv2.cvtColor(image_cropped, cv2.COLOR_BGR2RGB)``` is needed when ```image_cropped``` is ```None```

**Comment by shrubb** [comment]
Maybe, not sure. Anyway, if a face isn't detected (which already happens quite rarely), then the match score is going to be so large that BGR/RGB won't matter much.
Thanks for the comments.

**Comment by khlee369** [comment]
Thank you for the reply! :)
