### ISSUE TITLE
How can I see the effect of this code running. 

### ISSUE THREAD

**Issue by pfeducode** [shrubb/latent-pose-reenactment#38]
How can I see the effect of this code running.   Readme.md only shows how to train.

**Comment by shrubb** [comment]
No: https://github.com/shrubb/latent-pose-reenactment#running-the-pretrained-model

**Comment by pfeducode** [comment]
> 否：[https ://github.com/shrubb/latent-pose-reenactment#running-the-pretrained-model](https://github.com/shrubb/latent-pose-reenactment#running-the-pretrained-model)
when I  run drive.py, I get a problem that expected Ptr <cv:UMat> for argument 'dst'
![1](https://user-images.githubusercontent.com/100210045/168512554-8f33998a-0b89-408c-9406-d747fd12a55f.png)

**Comment by pfeducode** [comment]
> > 否：https://github.com/shrubb/latent-pose-reenactment#running-the-pretrained-model
> > 当我运行 drive.py 时，我遇到了一个问题，预期 Ptr cv:UMat for argument 'dst'
> > ![1](https://user-images.githubusercontent.com/100210045/168512554-8f33998a-0b89-408c-9406-d747fd12a55f.png)

**Comment by pfeducode** [comment]
> > 否：https://github.com/shrubb/latent-pose-reenactment#running-the-pretrained-model
> > 当我运行 drive.py 时，我遇到了一个问题，预期 Ptr cv:UMat for argument 'dst'
> > ![1](https://user-images.githubusercontent.com/100210045/168512554-8f33998a-0b89-408c-9406-d747fd12a55f.png)

I  solved the problem with reference to the following:
https://github.com/shrubb/latent-pose-reenactment/issues/4

my solution is to remove dst=img, and it work well
