### ISSUE TITLE
Have no access to all checkpoints

### ISSUE THREAD

**Issue by Unkrible** [shrubb/latent-pose-reenactment#42]
Hello!
Thank you for the open-source code.
However, I have no access to all the checkpoints on Google Driver.

**Comment by shrubb** [comment]
Hello. My Google Drive has been deleted so the checkpoints are lost... 😢 

Could you please find a person who has the checkpoint, and then share it with me so I could re-upload? For example, contact someone who posted in the "Issues"

**Comment by Unkrible** [comment]
Thank you~
I will try my best :).
It's a pity of losing all the checkpoints for such a good work.

**Comment by shrubb** [comment]
Hey @Unkrible, I believe I've restored the checkpoints. One of the international researchers has kindly sent them to me. Could you please tell me if you are able to download them now?

**Comment by Unkrible** [comment]
Hello! I'm able to download them now.
Thank you so much :)!
