### ISSUE TITLE
Training progress slow

### ISSUE THREAD

**Issue by monic7** [shrubb/latent-pose-reenactment#43]
Hi shrubb, I tried running the default code on 2 RTX3080 GPUs with default settings to train from scratch with data/splits/train.csv as the identites, but the training time is taking very long (at least 7.04 seconds per iteration, so 1 epoch takes at least 24 hours). 
I tried changing num_workers to 0, pin_memory in the dataloader to True and decreasing batch size but it still faces the same issue. 
Would like to enquire if theres any way to speed up training process?
Thanks

**Comment by shrubb** [comment]
Hi, 7 seconds per iteration is definitely too much. I had at least 10× less on two P40.

So looks like it's something specific to your setup, not sure what exactly... You can use Python's drop-in profiler with num_workers=0 (normally it should be >0) to examine what's taking so much time.
