### ISSUE TITLE
Set up to replicate the reenactment results in the paper 

### ISSUE THREAD

**Issue by Blade6570** [shrubb/latent-pose-reenactment#7]
Hi, 
I am trying to replicate the pose reconstruction error and identity error reported in the paper. The instruction in this repo involves some amount of user's judgement in the fine tuning to get the best results. 

Is there any default settings to generate the results in the paper? That would be good to test this model on number of videos for a fair comparison to other counter parts. 

Thanks

**Comment by shrubb** [comment]
Hi! You can check the [actual code that we used to compute metrics](https://github.com/shrubb/latent-pose-reenactment/blob/master/batched_finetune.py). It has those parameters. 'batched_drive.py' and 'compute_pose_identity_error.py' may also help.

**Comment by Blade6570** [comment]
Thanks for pointing to those files. It is working perfectly.
