### ISSUE TITLE
Generating an output sequeuence using a driving video and a source frame.

### ISSUE THREAD

**Issue by saksham-s** [shrubb/latent-pose-reenactment#8]
Is there a simple way to run the pretrained model to generate an output sequence corresponding to a driving video and a single source frame? The dataset I am working with is Voxceleb itself.

**Comment by shrubb** [comment]
Hi, yes, have you tried following the manual in README.md?

**Comment by saksham-s** [comment]
Is there a way to not fine-tune and run it directly? It will be a fair comparison to how I am evaluating my approach.

**Comment by shrubb** [comment]
Yes, just spend 0 iterations fine-tuning in those instructions. I mean set the number to 0 explicitly. If that doesn't work, set it to 1 (and if you want also set learning rates to 0).

**Comment by saksham-s** [comment]
Got it thanks!
